# Generated by Django 5.0 on 2025-03-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
    ]
